CREATE MATERIALIZED VIEW vstaUsuarioLocal AS
SELECT 		LOCALIDAD.NOMBRELOCALIDAD, COUNT(DISTINCT USUARIO.DOCUMENTOUSUARIO) AS CANTUSR,
			COUNT(DISTINCT MASCOTA.CODIGOMASCOTA) AS CANTMASC
FROM 		USUARIO
INNER JOIN	BARRIO
ON			USUARIO.CODIGOBARRIO = BARRIO.CODIGOBARRIO
INNER JOIN 	LOCALIDAD
ON			BARRIO.CODIGOLOCALIDAD = LOCALIDAD.CODIGOLOCALIDAD
INNER JOIN 	MASCOTA
ON			USUARIO.DOCUMENTOUSUARIO = MASCOTA.DOCUMENTOUSUARIO
WHERE 		USUARIO.CODIGOROL = 'ROL001'
GROUP BY 	LOCALIDAD.NOMBRELOCALIDAD;
